DISK="/dev/sda"
EFI_PART="/dev/sda1"
ROOT_PART="/dev/sda2"

FS_TYPE="btrfs"
FORMAT_ESP="yes"
MOUNT_OPTIONS="noatime,compress=zstd"

INSTALL_HYPRLAND="yes"
GPU="amd"
INSTALL_PARU="yes"
INSTALL_HOMEFILES="yes"

HOSTNAME="arch"
TIMEZONE="Europe/Samara"
USERNAME="clown"
TARGET_DIR="/opt/custarch"
