#################
### AUTOSTART ###
#################

# Status bar
exec-once = ~/.config/waybar/scripts/launch.sh

# Wallpaper
exec-once = swww-daemon
exec-once = sleep 1 && ~/.config/hypr/scripts/wallpaper.sh

# Notifications
exec-once = swaync

# Network
exec-once = nm-applet --indicator

# Bluetooth
exec-once = blueman-applet

# Idle manager
exec-once = hypridle

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Polkit
exec-once = systemctl --user start hyprpolkitagent

# Auto-mounting
exec-once = udiskie
