# Profiles Config for Clash Verge

current: LptZuzTz990R
items:
- uid: Merge
  type: merge
  name: null
  file: Merge.yaml
  updated: 1773069353
- uid: Script
  type: script
  name: null
  file: Script.js
  updated: 1773069353
- uid: mezacP3oYNQZ
  type: merge
  name: null
  file: mezacP3oYNQZ.yaml
  updated: 1773069420
- uid: sD5QA2QNXDps
  type: script
  name: null
  file: sD5QA2QNXDps.js
  updated: 1773069420
- uid: rFUdeeDewRRW
  type: rules
  name: null
  file: rFUdeeDewRRW.yaml
  updated: 1773069420
- uid: piLkKOHzX9HJ
  type: proxies
  name: null
  file: piLkKOHzX9HJ.yaml
  updated: 1773069420
- uid: gqHnELT3dZQO
  type: groups
  name: null
  file: gqHnELT3dZQO.yaml
  updated: 1773069420
- uid: LptZuzTz990R
  type: local
  name: mooo.yaml
  file: LptZuzTz990R.yaml
  desc: ''
  updated: 1773069420
  option:
    allow_auto_update: true
    merge: mezacP3oYNQZ
    script: sD5QA2QNXDps
    rules: rFUdeeDewRRW
    proxies: piLkKOHzX9HJ
    groups: gqHnELT3dZQO
