# lib/paths.sh
: "${ROOT_DIR:?ROOT_DIR is not set}"

ROOT_DIR="$(cd -- "$ROOT_DIR" && pwd -P)"
STAGES_DIR="$ROOT_DIR/stages"
LIVE_DIR="$STAGES_DIR/live"
CHROOT_DIR="$STAGES_DIR/chroot"
POST_DIR="$STAGES_DIR/post"
POST_ROOT_DIR="$POST_DIR/root"
POST_USER_DIR="$POST_DIR/user"
LIB_DIR="$ROOT_DIR/lib"
CONFIG_FILE="$ROOT_DIR/settings.conf"
LOG_FILE="$ROOT_DIR/install.log"
ASSETS_DIR="$ROOT_DIR/assets"
CONFIG_DIR="$ASSETS_DIR/configs"
LOCAL_DIR="$ASSETS_DIR/local"

export ROOT_DIR STAGES_DIR LIVE_DIR CHROOT_DIR POST_DIR POST_ROOT_DIR POST_USER_DIR
export LIB_DIR CONFIG_FILE LOG_FILE ASSETS_DIR CONFIG_DIR LOCAL_DIR
