#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us,ru
    kb_variant =
    kb_model =
    kb_options = grp:alt_shift_toggle
    kb_rules =

    follow_mouse = 1
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat

    touchpad {
        natural_scroll = true
        tap-to-click = true
        tap-and-drag = true
        drag_lock = false
        disable_while_typing = true
        clickfinger_behavior = true
        scroll_factor = 1.0
    }
}

gestures {
    # 3 пальца — переключение workspace
    gesture = 3, horizontal, workspace

    # 3 пальца вверх — fullscreen
    gesture = 3, up, fullscreen

    # 3 пальца вниз — float window
    gesture = 3, down, float
}

cursor {
    no_hardware_cursors = false
}

# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
