#################
### AUTOSTART ###
#################

# Status bar
exec-once = waybar

# Wallpaper
exec-once = hyprpaper

# Notifications
exec-once = dunst

# Network
exec-once = nm-applet --indicator

# Bluetooth
exec-once = blueman-applet

# Idle manager
exec-once = hypridle

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Polkit
exec-once = lxqt-policykit-agent
