##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# dialogs
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = center,class:^(pavucontrol)$

windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = center,class:^(nm-connection-editor)$

windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = center,class:^(blueman-manager)$

# file dialogs
windowrulev2 = float,title:^(Open File)$
windowrulev2 = center,title:^(Open File)$

# picture in picture
windowrulev2 = float,title:^(Picture-in-Picture)$
windowrulev2 = pin,title:^(Picture-in-Picture)$
windowrulev2 = size 400 300,title:^(Picture-in-Picture)$
